Create database PMHTNH
Go 
use PMHTNH
go 
CREATE TABLE CHUCVU
(
	MACV INT IDENTITY (1,1) PRIMARY KEY,
	TENCV NVARCHAR(30) NOT NULL, 
)
GO 
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) NOT NULL PRIMARY KEY,
	TENNV NVARCHAR(50) NOT NULL ,
	MACV INT NOT NULL REFERENCES CHUCVU(MACV),
	SDT VARCHAR (11) ,
	CMND VARCHAR (10),
	NSINH DATE CHECK (YEAR(NSINH) < YEAR(GETDATE()) ),
	GTINH BIT DEFAULT 1,
	NVSTT BIT NOT NULL DEFAULT 1
)
GO
CREATE TABLE TAIKHOAN
(
	ID INT IDENTITY PRIMARY KEY,
	TENTK VARCHAR(50) NOT NULL ,
	MANV VARCHAR (10) NOT NULL REFERENCES NHANVIEN (MANV),
	MATKHAU VARCHAR (50) NOT NULL,
	TENHIENTHI NVARCHAR(50) NOT NULL,
	TKSTT BIT NOT NULL DEFAULT 1

)
GO
CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(5) NOT NULL PRIMARY KEY,
	TENNCC NVARCHAR(50) NOT NULL ,
	SDT VARCHAR (11) NOT NULL,
	DCHI NVARCHAR(50) NOT NULL,
	NCCSTT BIT   NOT NULL DEFAULT 1
)
GO 
CREATE TABLE LOAINGUYENLIEU
(
	MALOAINL INT IDENTITY(1,1) PRIMARY KEY,
	MANCC VARCHAR(5) NOT NULL REFERENCES NHACUNGCAP(MANCC),
	TENLOAINL NVARCHAR(50) NOT NULL,
	LNLSTT BIT NOT NULL DEFAULT 1
)
GO 
CREATE TABLE NGUYENLIEU
(
	MANL VARCHAR(10) NOT NULL PRIMARY KEY,
	MALOAINL INT NOT NULL REFERENCES LOAINGUYENLIEU (MALOAINL),
	TENNL NVARCHAR(50) NOT NULL,
	GIA MONEY,
	NLSTT BIT NOT NULL DEFAULT 1
)
GO
CREATE TABLE PHIEUNHAP
(
	MAPN INT IDENTITY(1,1) PRIMARY KEY,
	MANV VARCHAR (10) NOT NULL REFERENCES NHANVIEN(MANV),
	NGAYLAP DATE NOT NULL DEFAULT GETDATE(),
	TONGGIANL MONEY NOT NULL,
	PNSTT BIT NOT NULL DEFAULT 1
)
GO
CREATE TABLE CTPN
(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	MAPN INT NOT NULL REFERENCES PHIEUNHAP(MAPN),
	MANL VARCHAR(10) NOT NULL REFERENCES NGUYENLIEU(MANL),
	SOLUONG INT DEFAULT 0 
)
CREATE TABLE KHO
(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	MANL VARCHAR(10) NOT NULL REFERENCES NGUYENLIEU(MANL),
	IDPN INT REFERENCES CTPN(ID),
	SLTON INT NOT NULL,
	
)
GO
CREATE TABLE BANAN 
(
	MABAN INT IDENTITY (1,1) PRIMARY KEY,
	TENBAN NVARCHAR(5) NOT NULL,
	TRANGTHAI NVARCHAR(10) DEFAULT 'Trống', 
	BANSTT BIT NOT NULL DEFAULT 1
)
GO 
CREATE TABLE LOAIMON
(
	MaLoaiMon int identity primary key,
	TenLoaiMon nvarchar(50),
	LMstatus bit,
)
go
create table MONAN
(
	MaMon varchar(10) primary key,
	TenMon nvarchar(50),
	MaLoaiMon int NOT NULL REFERENCES LOAIMON(MaLoaiMon),
	Gia decimal,
	HinhAnh image,
	MAstatus bit,
)
go

create table DONHANG
(
	MaHD int identity primary key,
	TongHD decimal,
	TienThu decimal,
	TienTra decimal,
	NgayXuat date,
	MaBan int not null references BANAN(MABAN),
	MaNV varchar(10) not null references NHANVIEN(MANV),
	KhuyenMai decimal,
)
go

create table CTHD
(
	id int identity primary key,
	MaHD int not null references DONHANG(MaHD),
	MaMon varchar(10) references MONAN(MaMon),
	TenMon nvarchar(50),
	SoLuong int,
)


insert into CHUCVU values(N'Quản lý' )
insert into NHANVIEN values('QL01',N'QUANLY01',2,0,0,'12/25/2000',1,1)
INSERT INTO TAIKHOAN VALUES ('QL1','QL01','1234',N'Quốc Việt',1)



insert into CHUCVU values(N'Nhân viên' )
insert into NHANVIEN values('NV01',N'NHANVIEN01',3,0,0,'12/25/2000',1,1)
INSERT INTO TAIKHOAN VALUES ('NV1','NV01','1234',N'Quốc Việt STAFF',1)
